function [timestamp, timegap] = readts(filepath)

% read frame timestamps from a txt file
% the txt file is generated by C++ code which uses OpenCV to read the video file

fid = fopen(filepath);
timestamp = fscanf(fid,'%f');
timestamp = timestamp./1000; % convert unit from 'msec' to 'sec'
timegap = diff(timestamp);
fclose(fid);


